name: works_fm
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter

  core:
    git:
      url: https://github.com/sanchezdev24/core_mobile
      ref: development
      
  auth:
    path: packages/auth
  dashboard:
    path: packages/dashboard

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
