name: auth
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: ^3.11.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    git:
      url: https://github.com/sanchezdev24/core_mobile
      ref: development

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true 